### ISSUE TITLE
ArgumentError when specifying queue argument as symbol

### ISSUE THREAD

**Issue by joeyAghion** [gemhome/sidekiq-delay_extensions#10]
After upgrading to sidekiq v7, simple `.delay(queue: ...)` calls raise an error:

```ruby
String.delay(queue: 'nondefault').to_s

Exception: ArgumentError: Job payloads should contain no Symbols: {"class"=>Sidekiq::DelayExtensions::DelayedClass, "args"=>["---\n- !ruby/class 'String'\n- :to_s\n- []\n"], "display_class"=>"String.to_s", :queue=>"nondefault"}
--
0: /Users/joey/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sidekiq-7.1.1/lib/sidekiq/job.rb:353:in `client_push'
1: /Users/joey/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sidekiq-delay_extensions-6.4.1/lib/sidekiq/delay_extensions/generic_proxy.rb:27:in `method_missing'
2: (pry):1:in `<main>'
3: /Users/joey/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:290:in `eval'
4: /Users/joey/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:290:in `evaluate_ruby'
```

Passing the `queue` argument as a string works:
```ruby
String.delay('queue' => 'nondefault').to_s # => "93885224a91a6e76c7a08f73"
```

This is probably just an oversight pending a v7 of this library, but I thought I'd create this issue before digging in further. 

### Context

Ruby version: `3.0.2`
Rails version: `6.1.7.2`
Sidekiq version(s): 7.1.1

```yaml
# sidekiq.yml
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 5 } %>
:queues:
  - default
  - mailers
  - low
```

```ruby
# config/initializers/sidekiq.rb
Sidekiq::DelayExtensions.enable_delay!
```

**Comment by bf4** [comment]
Thanks

**Comment by bf4** [comment]
I think this is fixed now.

**Comment by bf4** [comment]
I think it should work perfectly for you on the latest 7.1.0 release

**Comment by bf4** [comment]
Closing as resolved. Please re-open if you're still experiencing the issue.
