### ISSUE TITLE
Tried to load unspecified class Error

### ISSUE THREAD

**Issue by heaven** [gemhome/sidekiq-delay_extensions#9]
Ruby version: 3.1.4
Rails version: 6.1.7.3
Sidekiq / Pro / Enterprise version(s): 6.5.8

```
     Psych::DisallowedClass:
       Tried to load unspecified class: BigDecimal
     # (eval):2:in `big_decimal'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-delay_extensions-6.4.1/lib/sidekiq/delay_extensions/active_record.rb:21:in `perform'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-6.5.8/lib/sidekiq/testing.rb:301:in `execute_job'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-6.5.8/lib/sidekiq/testing.rb:296:in `block in process_job'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-6.5.8/lib/sidekiq/middleware/chain.rb:172:in `invoke'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-6.5.8/lib/sidekiq/testing.rb:295:in `process_job'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-6.5.8/lib/sidekiq/testing.rb:89:in `block in raw_push'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-6.5.8/lib/sidekiq/testing.rb:85:in `each'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-6.5.8/lib/sidekiq/testing.rb:85:in `raw_push'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-6.5.8/lib/sidekiq/client.rb:79:in `push'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-6.5.8/lib/sidekiq/worker.rb:360:in `client_push'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-delay_extensions-6.4.1/lib/sidekiq/delay_extensions/generic_proxy.rb:27:in `method_missing'
     # ./app/models/order.rb:323:in `notify_subject'
     # ./spec/models/charge_spec.rb:18:in `block (4 levels) in <top (required)>'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-6.5.8/lib/sidekiq/testing.rb:16:in `__set_test_mode'
     # /Users/heaven/.rvm/gems/ruby-3.1.4@qarib/gems/sidekiq-6.5.8/lib/sidekiq/testing.rb:34:in `inline!'
     # ./spec/models/charge_spec.rb:15:in `block (3 levels) in <top (required)>'
```

The problem is on this line https://github.com/gemhome/sidekiq-delay_extensions/blob/main/lib/sidekiq/delay_extensions/active_record.rb#L21

Most likely should use `YAML.safe_load` and `permitted_classes: ActiveRecord::Base.yaml_column_permitted_classes`.

**Comment by andrey-lizunov** [comment]
Right, we need `safe_load` and seems that we should add some ability to specify a list of permitted_classes and also an aliases param.
What do the gem maintainers think about this?

**Comment by bf4** [comment]
Sounds good. I have a patch for this in our app, i think, too.

**Comment by andrey-lizunov** [comment]
What do you think about something like [that](https://github.com/gemhome/sidekiq-delay_extensions/pull/14)? 
I think it will be great to have an ability to configure such params for YAML#load method.

**Comment by andrey-lizunov** [comment]
Also additional example of an issue.
I got such error when Sidekiq tried to load yaml with such fields
```
- !ruby/object:ActiveModel::Attribute::FromDatabase\n        name: updated_at\n        value_before_type_cast: !ruby/object:ActiveSupport::TimeWithZone\n          utc: 2023-09-28 16:05:11.687786000 Z\n          zone: *1\n          time: 2023-09-28 16:05:11.687786000 Z\n
```
So I got an error `Psych::DisallowedClass` connected with usage of Time class.

**Comment by heaven** [comment]
My quick looks like this:
```ruby
module Sidekiq
  module DelayExtensions

    # TODO: YAML.load error https://github.com/gemhome/sidekiq-delay_extensions/issues/9

    class DelayedModel
      def perform(yml)
        (target, method_name, args) = YAML.respond_to?(:unsafe_load) ? YAML.unsafe_load(yml) : YAML.load(yml)
        target.__send__(method_name, *args)
      end
    end
  end
end
```
But I agree it would be better to either respect `config.active_record.yaml_column_permitted_classes` setting or have a custom one.

**Comment by andrey-lizunov** [comment]
We also have aliases param which we don't have in Rails config. It's false by default but for some developers it will be needed.

**Comment by bf4** [comment]
Here's what I have right now in lib/extensions/sidekiq.rb which is an eager loaded file in our app

related to https://github.com/gemhome/sidekiq-delay_extensions/issues/8

```ruby
module Sidekiq
  # FIXME(BF): Until https://github.com/gemhome/sidekiq-delay_extensions/issues/8
  # is addressed
  class JobRecord
    private

    # per https://github.com/mperham/sidekiq/blob/v6.5.8/lib/sidekiq/api.rb#L492-L502
    # vs.
    # https://github.com/mperham/sidekiq/blob/v7.0.1/lib/sidekiq/api.rb#L374-L411
    def safe_load(content, default)
      yield(*YAML.load(content))
    rescue => ex
      # #1761 in dev mode, it's possible to have jobs enqueued which haven't been loaded into
      # memory yet so the YAML can't be loaded.
      Sidekiq.logger.warn "Unable to load YAML: #{ex.message}" unless Sidekiq.options[:environment] == "development"
      default
    end
  end
end
```

and also in lib/extensions/sidekiq.rb something like

```ruby
module Sidekiq
    DelayedClass.class_eval do
      # https://github.com/gemhome/sidekiq-delay-extensions/blob/v6.4.0/lib/sidekiq/extensions/class_methods.rb
      def perform(yml)
        (target, method_name, args, kwargs) = ::YAML.unsafe_load(yml)
        if target.is_a?(String)
          target_klass = target.safe_constantize
          if target_klass
            target = target_klass
          else
            fail NameError, "uninitialized constant #{target}. Peforming: #{yml.inspect}"
          end
        end
        has_no_kwargs = kwargs.nil? || kwargs.empty? # rubocop:disable Rails/Blank
        if has_no_kwargs
          if args.is_a?(Array) && args.last.is_a?(Hash) # && args.last.keys.any? { |key| key.is_a?(Symbol) }
            # rehydrate keys
            kwargs = args.pop.symbolize_keys
            has_no_kwargs = kwargs.empty?
          elsif args.is_a?(Hash)
            # rehydrate keys
            kwargs = args.symbolize_keys
            args = []
            has_no_kwargs = kwargs.empty?
          end
        end
        if has_no_kwargs
          ExceptionNotifier.append_scope!(sidekiq: {target: target, method_name: method_name, args: args})
        else
          ExceptionNotifier.append_scope!(sidekiq: {target: target, method_name: method_name, args: args, kwargs: kwargs})
        end
        return if ApplicationWorker.cancelled?(jid)
        return if ApplicationWorker.cancelled_batch?(bid, self)
        annotation_context = "#{target}.#{method_name}(*#{args.inspect}, **#{kwargs.inspect})"
        Marginalia.with_annotation(annotation_context) do
          if has_no_kwargs
            target.__send__(method_name, *args)
          else
            target.__send__(method_name, *args, **kwargs)
          end
        end
      end
    end
end
```

**Comment by bf4** [comment]
I think it should work perfectly for you on the latest 7.1.0 release

**Comment by bf4** [comment]
Closing as resolved. Please re-open if you're still experiencing the issue.
